#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Package
###################################################################################################
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "package.fullname" . | replace "." "" }}
  labels:
    app.kubernetes.io/name: {{ include "package.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dronedelivery
    helm.sh/chart: {{ include "package.chart" . }}
  annotations:
    kubernetes.io/change-cause: {{ .Values.reason }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "package.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "package.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: dronedelivery
        helm.sh/chart: {{ include "package.chart" . }}
    spec:
      containers:
      - name: &package-container_name fabrikam-package
        image: {{ .Values.dockerregistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: mongodb-pwd
        - name: COLLECTION_NAME
          value: {{ default "packages" .Values.cosmosDb.collectionName }}
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: appinsights-ikey
        - name: LOG_LEVEL
          value: {{ .Values.log.level }}
        - name: CONTAINER_NAME
          value: *package-container_name
        ports:
        - name: service
          containerPort: 80
