dependencies:
  - name: workflow-dev
    repository: "file://charts/workflow-dev"
    version: ">= 0.0.1"
    tags:
      - dev
    import-values:
      - data

  - name: workflow-prod
    repository: "file://charts/workflow-prod"
    version: ">= 0.0.1"
    tags:
      - prod
    import-values:
      - data

  - name: workflow-qa
    repository: "file://charts/workflow-qa"
    version: ">= 0.0.1"
    tags:
      - qa
    import-values:
      - data

  - name: workflow-staging
    repository: "file://charts/workflow-staging"
    version: ">= 0.0.1"
    tags:
      - staging
    import-values:
      - data
