variables:
  BuildConfiguration: "Release"

name: $(build.sourceBranch)-$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  batch: true
  branches:
    include:

    # for new release to production: release flow strategy
    - release/package/v*

    - refs/relelase/package/v*

  paths:
     include:

     - /src/shipping/package/

resources:
- repo: self

jobs:

# CI
- job: packagejobci
  displayName: "Package CI"
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 90
  variables:
    fullCI: $[ startsWith(variables['build.sourceBranch'], 'refs/heads/release/package/v') ]
  steps:
  - script: echo $(fullCI)
    name: echovar
  - template: ./azure-pipelines-ci.yml
