steps:
- script: echo '##vso[task.setvariable variable=repositoryName]dronescheduler'
  name: setvarAzureContainerRegistry
- script: echo $(repositoryName)
  name: echovarRepositoryName

- script: echo '##vso[task.setvariable variable=chartPath]charts/dronescheduler'
  name: setvarChartPath
- script: echo $(chartPath)
  name: echovarChartPath

- script: echo '##vso[task.setvariable variable=buildContext]src/shipping'
  name: setvarBuildContext
- script: echo $(buildContext)
  name: echovarBuildContext

- script: echo '##vso[task.setvariable variable=dockerFileName]src/shipping/dronescheduler/Dockerfile'
  name: setvarDockerFileName
- script: echo $(dockerFileName)
  name: echovarDockerFileName

- script: echo '##vso[task.setvariable variable=releaseVersion]$(Build.SourceBranchName)'
  name: setvarReleaseVersion
- script: echo $(releaseVersion)
  name: echovarReleaseVersion

- script: echo '##vso[task.setvariable variable=aksNamespace]backend'
  name: setvarAKSNamespace
- script: echo $(aksNamespace)
  name: echovarAKSNamespace

- script: echo '##vso[task.setvariable variable=imageName]$(repositoryName):$(releaseVersion)'
  name: setvarImageName
- script: echo $(imageName)
  name: echovarImageName

- task: Docker@1
  condition: or(eq(variables['buildImage'],True),eq(variables['fullCI'],True))
  displayName: 'Build runtime image'
  inputs:

    azureSubscriptionEndpoint: $(AzureSubscription)

    azureContainerRegistry: $(AzureContainerRegistry)

    dockerFile: $(System.DefaultWorkingDirectory)/$(dockerFileName)

    includeLatestTag: false

    imageName: '$(imageName)'

    buildContext: $(buildContext)

    useDefaultContext: false

- task: Docker@1
  condition: eq(variables['fullCI'],True)
  displayName: 'Push runtime image'
  inputs:
    azureSubscriptionEndpoint: $(AzureSubscription)

    azureContainerRegistry: $(AzureContainerRegistry)

    command: 'Push an image'

    imageName: '$(imageName)'

    includeSourceTags: false

- task: HelmInstaller@0
  condition: eq(variables['fullCI'],True)
  displayName: 'Install Helm 2.9.1'
  inputs:
    kubectlVersion: 1.10.3

    checkLatestKubectl: false

- task: HelmDeploy@0
  condition: eq(variables['fullCI'],True)
  displayName: 'helm init --client-only'
  inputs:
    azureSubscription: $(AzureSubscription)

    azureResourceGroup: $(ResourceGroup)

    kubernetesCluster: $(AzureKubernetesService)

    command: init

    upgradeTiller: false

    arguments: '--client-only'

- task: HelmDeploy@0
  condition: eq(variables['fullCI'],True)
  displayName: 'helm package'
  inputs:
    command: package

    chartPath: $(chartPath)

    chartVersion: $(Build.SourceBranchName)

    arguments: '--app-version $(Build.SourceBranchName)'

- task: AzureCLI@1
  condition: eq(variables['fullCI'],True)
  displayName: 'Push a helm package'
  inputs:
    azureSubscription: $(AzureSubscription)

    scriptLocation: inlineScript

    inlineScript: |
     az acr helm push $(System.ArtifactsDirectory)/$(repositoryName)-$(Build.SourceBranchName).tgz --name $(AzureContainerRegistryHelmRepo) --force;
