apiVersion: v2
name: package
version: v0.1.0
appVersion: v0.1.0
description: Fabrikam Drone Delivery Package Service
dependencies:
  - name: package-dev
    repository: "file://envs/package-dev"
    version: ">= 0.0.1"
    tags:
      - dev
    import-values:
      - data
