# Default values for package service.
nameOverride: package
replicaCount: 1
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
log:
  level: error
cosmosDb:
  collectionName:
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false