# Default values for package service.
replicaCount: 3
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
log:
  level: error
cosmosDb:
  collectionName:
resources:
  requests:
    cpu: 300m
    memory: 100Mi
  limits:
    cpu: 410m
    memory: 140Mi
