#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Dronescheduler service identity
###################################################################################################
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: dronescheduler-identity
 annotations:
  "helm.sh/hook": "pre-install"
  "helm.sh/hook-weight": "0"
spec:
 type: 0
 ResourceID: {{ .Values.identity.resourceid }}
 ClientID: {{ .Values.identity.clientid }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
 name: dronescheduler-identity-binding
 annotations:
  "helm.sh/hook": "pre-install"
  "helm.sh/hook-weight": "1"
spec:
 AzureIdentity: dronescheduler-identity
 Selector: dronescheduler
