#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Delivery service
###################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery
    bc: shipping
    co: fabrikam
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: delivery
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: delivery
  labels:                 # In API version apps/v1beta2, .metadata.labels no longer default to .spec.template.metadata.labels.
    app: delivery
    version: 0.1.0
    bc: shipping
    co: fabrikam
    aadpodidbinding: delivery
spec:
  replicas: 1
  selector:                # In API version apps/v1beta2, .spec.selector no longer default to .spec.template.metadata.labels.
    matchLabels:           # spec.selector is immutable after creation of the Deployment in apps/v1beta2.
      app: delivery
  template:                # A Deployment may terminate Pods whose labels match the selector if their template is different from .spec.template
    metadata:
      labels:
        app: delivery
        version: 0.1.0
        bc: shipping
        co: fabrikam
        aadpodidbinding: delivery
      annotations:
        team: deliveryservice
    spec:
      securityContext:
        fsGroup: 1
      containers:
      - name: delivery
        image:
        volumeMounts:
        - name: delivery
          mountPath: /kvmnt
          readOnly: true
        env:
        # Export K8s secrets
        - name: DOCDB_KEY
          valueFrom:
            secretKeyRef:
              name: delivery-storageconf
              key: CosmosDB_Key
        - name: DOCDB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: delivery-storageconf
              key: CosmosDB_Endpoint
        - name: DOCDB_DATABASEID
          value: "CosmosDB_DatabaseId"
        - name: DOCDB_COLLECTIONID
          value: "CosmosDB_CollectionId"
        - name: KEY_VAULT_URI
          value: "KeyVault_Name"
        - name: REDIS_ENDPOINT
          valueFrom:
             secretKeyRef:
              name: delivery-storageconf
              key: Redis_Endpoint
        - name: REDIS_KEY
          valueFrom:
             secretKeyRef:
              name: delivery-storageconf
              key: Redis_AccessKey
        - name: EH_CONNSTR
          valueFrom:
             secretKeyRef:
              name: delivery-storageconf
              key: EH_ConnectionString
        - name: EH_ENTITYPATH
          value: "EH_EntityPath"
        - name: no_proxy
          value: 169.254.169.254
        ports:
        - name: service
          containerPort: 8080
        resources:
           requests:
             cpu: 1
             memory: 2G
           limits:
             cpu: 1
             memory: 3G
      volumes:
      - name: delivery
        flexVolume:
          driver: "azure/kv"
          options:
            usepodidentity: "true"
            keyvaultname: "keyVaultName"
            keyvaultobjectnames: CosmosDB-Key;CosmosDB-Endpoint;Redis-Endpoint;Redis-AccessKey
            keyvaultobjecttypes: secret;secret;secret;secret
            keyvaultobjectversions: ""
            resourcegroup: "keyVaultResourceGroup"
            subscriptionid: "keyVaultSubscriptionId"
            tenantid: "keyVaultTenantId"
