##################################################################################################
# Ingestion service
##################################################################################################
apiVersion: v1
kind: Secret
metadata:
  name: dd-ingestion-conf
type: Opaque
data:
  EVENTHUB_NAMESPACE: eventhubnamespacebase64
  EVENTHUB_NAME: eventhubnamebase64
  EVENTHUB_KEYNAME: eventhubkeybase64
  EVENTHUB_KEYVALUE: eventhubkeybase64
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: ingestion
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: ingestion
        version: v1
    spec:
      containers:
      - name: ingestion
        image: image
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/probe
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
        - name: EH_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: dd-ingestion-conf
              key: EVENTHUB_NAMESPACE
        - name: EH_NAME
          valueFrom:
            secretKeyRef:
              name: dd-ingestion-conf
              key: EVENTHUB_NAME
        - name: EH_KEYNAME
          valueFrom:
            secretKeyRef:
              name: dd-ingestion-conf
              key: EVENTHUB_KEYNAME
        - name: EH_KEYVALUE
          valueFrom:
            secretKeyRef:
              name: dd-ingestion-conf
              key: EVENTHUB_KEYVALUE
        - name: NODE_NAME
          valueFrom:
           fieldRef:
            fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
           fieldRef:
            fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
      imagePullSecrets:
        - name: dockersecret

        
