#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

##################################################################################################
# Ingestion service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app: ingestion
    bc: shipping
    co: fabrikam
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ingestion
  type:
    ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingestion-ingress
spec:
  tls:
  - hosts:
    - ingestion-host-name
    secretName: ingestion-ingress-tls
  rules:
  - host: ingestion-host-name
    http:
      paths:
      - path: /
        backend:
          serviceName: ingestion
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestion
  labels:
    app: ingestion
    version: 0.1.0
    bc: shipping
    co: fabrikam
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingestion
        version: 0.1.0
        bc: shipping
        co: fabrikam
    spec:
      containers:
      - name: ingestion
        image:
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/probe
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
        - name: QUEUE_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: queue_namespace
        - name: QUEUE_NAME
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: queue_name
        - name: QUEUE_KEYNAME
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: queue_keyname
        - name: QUEUE_KEYVALUE
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: queue_keyvalue
