#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

##################################################################################################
# Ingestion service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app: ingestion
    bc: shipping
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: ingestion
  type: 
    LoadBalancer 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 15
  template:
    metadata:
      labels:
        app: ingestion
        version: v1
    spec:
      containers:
      - name: ingestion
        image:
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/probe
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20
        env:
        - name: EH_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: EVENTHUB_NAMESPACE
        - name: EH_NAME
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: EVENTHUB_NAME
        - name: EH_KEYNAME
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: EVENTHUB_KEYNAME
        - name: EH_KEYVALUE
          valueFrom:
            secretKeyRef:
              name: ingestion-secrets
              key: EVENTHUB_KEYVALUE
        - name: NODE_NAME
          valueFrom:
           fieldRef:
            fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
           fieldRef:
            fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140