#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package
  labels:
    app: package
    version: 0.1.0
    bc: shipping
    co: fabrikam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: package
  template:
    metadata:
      labels:
        app: package
        version: 0.1.0
        bc: shipping
        co: fabrikam
    spec:
      containers:
      - name: &package-container_name package
        image:
        env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: package-secrets
              key: mongodb-pwd
        - name: COLLECTION_NAME
          value: packages
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: package-secrets
              key: appinsights-ikey
        - name: LOG_LEVEL
          value: error
        - name: CONTAINER_NAME
          value: *package-container_name
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: package
  labels:
    app: package
    bc: shipping
    co: fabrikam
spec:
  selector:
    app: package
  ports:
  - name: http
    port: 80
