apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: scheduler
spec:
  serviceName: schedulerservice
  replicas: 5
  template:
    metadata:
      labels:
        app: schedulerservice
        run: schedulerservice
    spec:
      containers:
      - image: index.docker.io/kirpasingh/poltergeist:akka-scheduler84
        name: schedulerservice
        imagePullPolicy: Always
        env:
          - name: HOST_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: http_proxy
            value: $(NODE_NAME):4140	
          - name: SERVICEMESH_HEADERS
            value: l5d-ctx-deadline,l5d-ctx-trace
          - name: SERVICEMESH_CORRELATION_HEADER
            value: l5d-ctx-trace	
          - name: SERVICE_URI_ACCOUNT
            value: http://accountservice/api/Account
          - name: SERVICE_URI_DELIVERY
            value: http://deliveryservice/api/Deliveries
          - name: SERVICE_URI_DRONE
            value: http://droneservice/api/DroneDeliveries
          - name: SERVICE_URI_PACKAGE
            value: http://package/api/packages
          - name: SERVICE_URI_THIRDPARTY
            value: http://thirdpartyservice/api/ThirdPartyDeliveries
          - name: IOTHUB_EVENTHUB_NAME
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: eventHubName
          - name: IOTHUB_EVENTHUB_ENDPOINT
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: eventHubEndpoint
          - name: IOTHUB_ACCESS_CONNSTRING
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: eventHubConnectionString
          - name: IOTHUB_CHECKPOINT_AZSTORAGE_ACCOUNT
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: blobStorageAccountName
          - name: IOTHUB_CHECKPOINT_AZSTORAGE_KEY
            valueFrom:
              secretKeyRef: 
                name: scheduler-secrets
                key: blobStorageAccountKey
          - name: IOTHUB_EVENTHUB_PARTITIONS
            value: "13"
      imagePullSecrets:
        - name: poltergeistkey
---
apiVersion: v1
kind: Service
metadata:
  name: schedulerservice
spec:
  selector:
    app: schedulerservice
  ports:
    - port: 80
  type: NodePort
