apiVersion: v1
kind: Secret
metadata:
  name: scheduler-secrets
type: Opaque
data:
  eventHubName: bGlua2VyZGh1Yg==
  eventHubEndpoint: RW5kcG9pbnQ9c2I6Ly9kZWxpdmVyeXNjaGVkdWxlcm5zLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9Z0ZxRWs4ZEdRZ1poY0pNdW1qWlV2dnd2aFk1SnZvcHEwcWVJVWM4UW9FRT0=
  eventHubConnectionString: RW5kcG9pbnQ9c2I6Ly9kZWxpdmVyeXNjaGVkdWxlcm5zLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9Z0ZxRWs4ZEdRZ1poY0pNdW1qWlV2dnd2aFk1SnZvcHEwcWVJVWM4UW9FRT0=
  blobStorageAccountName: ZGVsaXZlcnlodWI=
  blobStorageAccountKey: K0gyYzZuZEh4R1R2ZVA3VjJ6WnB3aUNyTjZHRUhMUHl4eWJtdUo1bmdQRFoxRFM1NTRORW0wQWwrRVowb25DOGZkWlNjMmJtTlVPRERoV2Y2SlFzMXc9PQ==

