apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accountservice
spec:
  replicas: 5
  template:
    metadata:
      labels:
        run: accountservice
        app: accountservice
    spec:
      containers:
      - name: accountservice
        image: dronedelivery.azurecr.io/mockaccountservice
        ports:
          - containerPort: 80