# Staging values for ingestion.
nameOverride: ingestion
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "info"
    reason: "new staging deploy"
    nginx-ingress:
      controller:
        replicaCount: 2
    current: true
    resources:
      requests:
        cpu: 150m
        memory: 600Mi
      limits:
        cpu: 300m
        memory: 800Mi