# Staging values for dronescheduler.
nameOverride: dronescheduler
exports:
  data:
    replicaCount: 3
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new staging deploy"
    current: true
    resources:
      requests:
        cpu: 130m
        memory: 350Mi
      limits:
        cpu: 270m
        memory: 500Mi