apiVersion: v2
name: dronescheduler
version: v0.1.0
appVersion: v0.1.0
description: Fabrikam Drone Scheduler Service
type: application
home: https://docs.microsoft.com/azure/architecture/reference-architectures/microservices/aks
sources:
  - https://github.com/mspnp/microservices-reference-implementation
dependencies:
  - name: dronescheduler-dev
    repository: "file://envs/dronescheduler-dev"
    version: ">= 0.0.1"
    tags:
      - dev
    import-values:
      - data
