# Default values for dronescheduler.
replicaCount: 1
identity:
  clientid:
  resourceid:
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
keyvault:
  uri:
cosmosdb:
  id:
  collectionid:
reason: unknown
telemetry:
  level: "Error"
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false