apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "delivery.fullname" . | replace "." "" }}
  labels:
    app.kubernetes.io/name: {{ include "delivery.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: dronedelivery
    helm.sh/chart: {{ include "delivery.chart" . }}
  annotations:
    kubernetes.io/change-cause: {{ .Values.reason }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "delivery.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "delivery.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: dronedelivery
        helm.sh/chart: {{ include "delivery.chart" . }}
    spec:
      containers:
      - name: deliveryservice
        image: {{ .Values.dockerregistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: DOCDB_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-dd-deliveryservice-cosmosdbconf
              key: CosmosDB_Key
        - name: DOCDB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-dd-deliveryservice-cosmosdbconf
              key: CosmosDB_Endpoint
        - name: DOCDB_DATABASEID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-dd-deliveryservice-cosmosdbconf
              key: CosmosDB_DatabaseId
        - name: DOCDB_COLLECTIONID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-dd-deliveryservice-cosmosdbconf
              key: CosmosDB_CollectionId
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
        - name: CORRELATION_HEADER
          value: {{ .Values.correlationheader }}
        ports:
        - name: service
          containerPort: 80
