variables:
  BuildConfiguration: "Release"
  
name: $(build.sourceBranch)-$(Date:yyyyMMdd)$(Rev:.rr)

pr: # only valid for GitHub. Using Azure repo it must be configure as a Branch Policy
  branches:
    include:

    - master

    - release/workflow/v* # for bug fixes

  paths:
    include:

    - /src/shipping/workflow/

trigger:
  batch: true
  branches:
    include:

    - master

    - feature/*

    - topic/*

    exclude:

    - feature/experimental/*

    - topic/experimental/*

  paths:
     include:

     - /src/shipping/workflow/

resources:
- repo: self

jobs:

# CI
- job: workflowcivalidationjob
  displayName: "Workflow CI Validation (build & test)"
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 90
  variables:
    fullCI: False
    buildImage: $[ or(startsWith(variables['build.sourceBranch'], 'refs/pull/'),eq(variables['build.sourceBranch'], 'refs/head/master')) ]
  steps:
  - template: ./azure-pipelines-ci.yml
