# Default values for ingestion.
replicaCount: 1
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
telemetry:
  level: "error"
resources:
  requests:
    cpu: 500m
    memory: 600Mi
  limits:
    cpu: 650m
    memory: 800Mi
