# Default values for ingestion.
replicaCount: 1
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
telemetry:
  level: "error"
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
