dependencies:
  - name: delivery-dev
    repository: "file://charts/delivery-dev"
    version: ">= 0.0.1"
    tags:
      - dev
    import-values:
      - data

  - name: delivery-prod
    repository: "file://charts/delivery-prod"
    version: ">= 0.0.1"
    tags:
      - prod
    import-values:
      - data

  - name: delivery-qa
    repository: "file://charts/delivery-qa"
    version: ">= 0.0.1"
    tags:
      - qa
    import-values:
      - data

  - name: delivery-staging
    repository: "file://charts/delivery-staging"
    version: ">= 0.0.1"
    tags:
      - staging
    import-values:
      - data
