# Default values for delivery.
nameOverride: delivery
replicaCount: 1
identity:
  clientid:
  resourceid:
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
cosmosdb:
  id:
  collectionid:
keyvault:
  uri:
telemetry:
  level: "Error"
reason: unknown
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
