# Default values for dronedelivery.
replicaCount: 3
identity:
  clientid:
  resourceid:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
cosmosdb:
  id:
  collectionid:
keyvault:
  uri:
telemetry:
  level: "Error"
reason: unknown
resources:
  requests:
    cpu: 350m
    memory: 350Mi
  limits:
    cpu: 500m
    memory: 500Mi
