# Default values for dronedelivery.
replicaCount: 1
identity:
  clientid:
  resourceid:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
cosmosdb:
  id:
  collectionid:
keyvault:
  uri:
telemetry:
  level: "Error"
reason: unknown
